import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Landing.module.scss'

function How_it_Works() {
  return (
    <div className={style.body}>
        <Head>
            <title>Terms & Services</title>
        </Head>
        <div className={style.c1} />
        <section className={style.cont}>
            <h1>
                Terms & Services
            </h1>
            <p>
                Last updated: May 15, 2022
            </p>
            <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.

            </p>
            <h2>
            Interpretation and Definitions
            </h2>
            <h3>
            Interpretation
            </h3>
            <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
            <h2>
            Definitions
            </h2>
            <h3>
            For the purposes of this Privacy Policy:
            </h3>
            <ul>
                <li>
                    Account means a unique account created for You to access our Service or parts of our Service.
                </li>
                <li>
                    Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                </li>
                <li>
                    Application means the software program provided by the Company downloaded by You on any electronic device, named Streamhub
                </li>
                <li>
                    Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Streamhub.
                </li>
                <li>
                    Country refers to: Mongolia
                </li>
                <li>
                    Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                </li>
                <li>
                    Personal Data is any information that relates to an identified or identifiable individual.
                </li>
                <li>
                    Service refers to the Application.
                </li>
                <li>
                    Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                </li>
                <li>
                    Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </li>
                <li>
                    You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </li>
            </ul>
            <h2>
                Collecting and Using Your Personal Data
            </h2>
            <h3>
                Types of Data Collected
            </h3>
            <h4>
                Personal Data
            </h4>
            <p>
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul>
                <li>Youtube ID</li>
                <li>Youtube Profile</li>
                <li>Facebook ID</li>
                <li>Facebook Profile</li>
                <li>Usage Data</li>
                <li>Youtube ID</li>
            </ul>
            <h3>
                Usage Data
            </h3>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.  
            </p>
            <p>
            We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
            </p>
        </section>
    <div className={style.c2} />
  </div>
  );
}

export default How_it_Works;